regen-codium-extensions:
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --remote
  image: "nixos/nix:latest"
  stage: deploy
  when: always
  script:
    - echo "experimental-features = nix-command flakes" >>/etc/nix/nix.conf
    - nix profile install --priority 1 nixpkgs#gawk nixpkgs#git nixpkgs#gnused nixpkgs#nix-search-cli
    - git config user.name "${MAIN_BOT_USERNAME}"
    - git config user.email "${MAIN_BOT_EMAIL}"
    - git remote remove gitlab_origin || true
    - git remote add gitlab_origin https://"${MAIN_BOT_USERNAME}":"${MAIN_BOT_TOKEN}"@"${CI_SERVER_FQDN}"/public-leo/"${CI_PROJECT_NAME}".git
    - git add ./home-manager/codium-extensions/nix4vscode
    - DATE="$(date +"%F-%H")"
    - |
      if git commit -m "Update submodule nix4vscode [ci skip] ${DATE}"; then
          git push -o ci.skip gitlab_origin HEAD:main
      fi
    - chmod 755 ./home-manager/codium-extensions/ci-regen-codium-extensions.sh
    - ./home-manager/codium-extensions/ci-regen-codium-extensions.sh
    - git add ./home-manager/codium-extensions/codium-extensions.nix ./home-manager/codium-extensions/config.toml
    - |
      if git commit -m "Regen codium-extensions.nix [ci skip] ${DATE}"; then
          git push -o ci.skip gitlab_origin HEAD:main
      fi
