regen-codium-extensions:
  image: "docker.io/ruby:latest"
  stage: deploy
  when: always
  script:
    - chmod +x ./home-manager/codium-extensions/.ci-update.sh
    - ./home-manager/codium-extensions/.ci-update.sh
    - git config user.name "$MAIN_BOT_USERNAME"
    - git config user.email "$MAIN_BOT_EMAIL"
    - git remote add gitlab_origin https://$MAIN_BOT_USERNAME:$MAIN_BOT_TOKEN@$CI_SERVER_FQDN/public-leo/$CI_PROJECT_NAME.git
    - git add ./home-manager/codium-extensions/codium-extensions.nix
    - DATE="$(/usr/bin/date +"%F-%H")"
    - git commit -m "Regen codium-extensions.nix - CI $DATE"
    - git push gitlab_origin HEAD:main -o ci.skip
