regen-codium-extensions:
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --remote
  image: "nixos/nix:latest"
  stage: deploy
  when: always
  script:
    - nix-env -iA nixos.git nixos.gawk nixos.nix-search-cli
    - chmod 755 ./home-manager/codium-extensions/.ci-update.sh
    - ./home-manager/codium-extensions/.ci-update.sh
    - git config user.name "${MAIN_BOT_USERNAME}"
    - git config user.email "${MAIN_BOT_EMAIL}"
    - git remote remove gitlab_origin || true
    - git remote add gitlab_origin https://${MAIN_BOT_USERNAME}:${MAIN_BOT_TOKEN}@${CI_SERVER_FQDN}/public-leo/${CI_PROJECT_NAME}.git
    - git add ./home-manager/codium-extensions/nix4vscode
    - git add ./home-manager/codium-extensions/codium-extensions.nix
    - git add ./home-manager/codium-extensions/config.toml
    - |
      DATE="$(/usr/bin/date +"%F-%H")"
      if git commit -m "Regen codium-extensions.nix - CI ${DATE}"; then
          git push gitlab_origin HEAD:main -o ci.skip
      fi
