#!/usr/bin/env bash

# Commands that should be applied only for interactive shells
[[ "${-}" != *i* ]] &&
    return

# Source /etc/bashrc
if [[ -f /etc/bashrc ]]; then
    # shellcheck source=/dev/null
    . /etc/bashrc
fi

# Source ~/.bash_aliases
if [[ -f ~/.bash_aliases ]]; then
    # shellcheck source=/dev/null
    . ~/.bash_aliases
fi

# Key bindings
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# History
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=10000
HISTFILESIZE=100000
shopt -s histappend

# Line wrap on window resize
shopt -s checkwinsize

# Tab completion for doas
command -v doas >/dev/null 2>&1 &&
    complete -F _command doas

# If GUI isn't available and not connected through ssh, don't do anything
[[ -z "${XDG_CURRENT_DESKTOP}" ]] && [[ -z "${SSH_CLIENT}" ]] && [[ -z "${SSH_TTY}" ]] &&
    return

# Prompt
if [[ "${TERM}" != "dumb" ]] && command -v /usr/bin/starship >/dev/null 2>&1; then
    eval "$(/usr/bin/starship init /bin/bash)"
fi

# List number of outdated packages
if command -v /usr/bin/checkupdates >/dev/null 2>&1; then
    UPDATES="$(/usr/bin/timeout 4 /usr/bin/checkupdates 2>/dev/null | /usr/bin/wc -l)"
    [[ "${UPDATES}" -gt 0 ]] &&
        /usr/bin/echo -e "\e[31m${UPDATES}\e[0m packages are out of date."
fi

# Avoid non 0 exit status
true
