import = ["/usr/share/gruvbox/gruvbox.toml"]
live_config_reload = true

[window]
padding = { x = 0, y = 0 }
decorations = "none"
decorations_theme_variant = "None"
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[font]
size = 10
normal = { family = "Noto Sans Mono", style = "Regular" }
bold = { family = "Noto Sans Mono", style = "Bold" }
italic = { family = "Noto Sans Mono", style = "Italic" }
bold_italic = { family = "Noto Sans Mono", style = "Bold Italic" }

[env]
TERM = "alacritty"
