# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
      {
        "yzhang"."markdown-all-in-one" = vscode-utils.extensionFromVscodeMarketplace {
          name = "markdown-all-in-one";
          publisher = "yzhang";
          version = "3.6.2";
          sha256 = "1n9d3qh7vypcsfygfr5rif9krhykbmbcgf41mcjwgjrf899f11h4";

        };
        "gitlab"."gitlab-workflow" = vscode-utils.extensionFromVscodeMarketplace {
          name = "gitlab-workflow";
          publisher = "gitlab";
          version = "6.2.2";
          sha256 = "0yg3mh7aa3plqmvxspikqjh9kfwggsm0zrq3dkhfvi545h6c6v5w";

        };
        "pkief"."material-product-icons" = vscode-utils.extensionFromVscodeMarketplace {
          name = "material-product-icons";
          publisher = "pkief";
          version = "1.7.1";
          sha256 = "1g75m55fc6nnfazpgmjxc48kw8abv85sglmmmjglwwgwi0di2xlj";

        };
        "franneck94"."vscode-c-cpp-dev-extension-pack" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-c-cpp-dev-extension-pack";
          publisher = "franneck94";
          version = "0.10.0";
          sha256 = "0dqyr8kyj6qj34x34x078b5xflhlzvi1k7ld3hzm1mf9l5y2mdgg";

        };
        "psioniq"."psi-header" = vscode-utils.extensionFromVscodeMarketplace {
          name = "psi-header";
          publisher = "psioniq";
          version = "1.25.1";
          sha256 = "0hsx8nghwcijdydy2wd16g4a1gz1d7lbyxszk1rz6k7wa36wzgya";

        };
        "gruntfuggly"."activitusbar" = vscode-utils.extensionFromVscodeMarketplace {
          name = "activitusbar";
          publisher = "gruntfuggly";
          version = "0.0.47";
          sha256 = "16ianj0cdnzmqnq3jnx5nd7yd9w0fmrzwdn3d2a1r7a5r05y9f44";

        };
        "zignd"."html-css-class-completion" = vscode-utils.extensionFromVscodeMarketplace {
          name = "html-css-class-completion";
          publisher = "zignd";
          version = "1.20.0";
          sha256 = "1hc2dgib3wryygb36h47wzf32iv1x6rn1swmbgchiyjw62jjj4fw";

        };
        "waderyan"."gitblame" = vscode-utils.extensionFromVscodeMarketplace {
          name = "gitblame";
          publisher = "waderyan";
          version = "11.1.2";
          sha256 = "1pics1k76ihb785bhcrlp8g8q5l9rxv8gp9nn9lhn9ddb74cqnsf";

        };
        "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "prettier-vscode";
          publisher = "esbenp";
          version = "11.0.0";
          sha256 = "1fcz8f4jgnf24kblf8m8nwgzd5pxs2gmrv235cpdgmqz38kf9n54";

        };
        "hangxingliu"."vscode-nginx-conf-hint" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-nginx-conf-hint";
          publisher = "hangxingliu";
          version = "0.3.1";
          sha256 = "0ssskps24anri14yvg7cg4xvc0mppw9vry20ki1si3m3q9rhfp5p";

        };
        "formulahendry"."code-runner" = vscode-utils.extensionFromVscodeMarketplace {
          name = "code-runner";
          publisher = "formulahendry";
          version = "0.12.2";
          sha256 = "0i5i0fpnf90pfjrw86cqbgsy4b7vb6bqcw9y2wh9qz6hgpm4m3jc";

        };
        "wingrunr21"."vscode-ruby" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-ruby";
          publisher = "wingrunr21";
          version = "0.28.0";
          sha256 = "1gab5cka87zw7i324rz9gmv423rf5sylsq1q1dhfkizmrpwzaxqz";

        };
        "htmlhint"."vscode-htmlhint" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-htmlhint";
          publisher = "htmlhint";
          version = "1.0.5";
          sha256 = "079rpiy0fxhzsd6cli4nxbl3r9kmw98wcjmssm304ab1f4ghlj1c";

        };
        "mtxr"."sqltools-driver-mssql" = vscode-utils.extensionFromVscodeMarketplace {
          name = "sqltools-driver-mssql";
          publisher = "mtxr";
          version = "0.4.4";
          sha256 = "1fznfdc2mk7g8pafdw3vzls69l0qv2wgcrmzxghyj5bsf06ig666";

        };
        "rdebugger"."r-debugger" = vscode-utils.extensionFromVscodeMarketplace {
          name = "r-debugger";
          publisher = "rdebugger";
          version = "0.5.5";
          sha256 = "0v45fbcpqgdlql4splslvccccrrsnrcxs1qqcx5bv7a0r6v9l7s5";

        };
        "ms-vscode"."live-server" = vscode-utils.extensionFromVscodeMarketplace {
          name = "live-server";
          publisher = "ms-vscode";
          version = "0.5.2024091601";
          sha256 = "1rhjz9jjfba7pfqq39f07mzmz5ifwpsgl7yd2qf30wacdqays2bk";

        };
        "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
          name = "go";
          publisher = "golang";
          version = "0.47.1";
          sha256 = "0b82wrrn2v2vssgxgbbk0g8q7b23njzhz99dyjnj3v8ffaywz9hl";

        };
        "swellaby"."vscode-rust-test-adapter" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-rust-test-adapter";
          publisher = "swellaby";
          version = "0.11.0";
          sha256 = "111vhl71zzh4il1kh21l49alwlllzcvmdbsxyvk9bq3r24hxq1r2";

        };
        "kokororin"."vscode-phpfmt" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-phpfmt";
          publisher = "kokororin";
          version = "1.2.41";
          sha256 = "033y599slnw73p8c23i4nxfn9rngi4gdr0mb0xr7vlc2ba5f0r4q";

        };
        "rebornix"."ruby" = vscode-utils.extensionFromVscodeMarketplace {
          name = "ruby";
          publisher = "rebornix";
          version = "0.28.1";
          sha256 = "179g7nc6mf5rkha75v7rmb3vl8x4zc6qk1m0wn4pgylkxnzis18w";

        };
        "vscjava"."vscode-java-pack" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-java-pack";
          publisher = "vscjava";
          version = "0.29.2024091906";
          sha256 = "110spdp0h0r82dn3aq2g68a4jdpcknqj7midsi6l8mlqm958fi83";

        };
        "franneck94"."workspace-formatter" = vscode-utils.extensionFromVscodeMarketplace {
          name = "workspace-formatter";
          publisher = "franneck94";
          version = "1.1.0";
          sha256 = "0rliczyvv7c3bpy1drksm31gha2sqp7x3v6v83y9gz2jq190m9bx";

        };
        "zhuangtongfa"."material-theme" = vscode-utils.extensionFromVscodeMarketplace {
          name = "material-theme";
          publisher = "zhuangtongfa";
          version = "3.19.0";
          sha256 = "1z3wiacb2m7hvpfhn6qs710lsaxpy7c56jbjckccvqi705w9firb";

        };
        "fwcd"."kotlin" = vscode-utils.extensionFromVscodeMarketplace {
          name = "kotlin";
          publisher = "fwcd";
          version = "0.2.36";
          sha256 = "1cwncjvarq3g0cmn9afdd15s81nms0kcawnj3midhr4hchap2aml";

        };
        "naumovs"."color-highlight" = vscode-utils.extensionFromVscodeMarketplace {
          name = "color-highlight";
          publisher = "naumovs";
          version = "2.8.0";
          sha256 = "14capk3b7rs105ij4pjz42zsysdfnkwfjk9lj2cawnqxa7b8ygcr";

        };
        "yzane"."markdown-pdf" = vscode-utils.extensionFromVscodeMarketplace {
          name = "markdown-pdf";
          publisher = "yzane";
          version = "1.5.0";
          sha256 = "109cmy62hgsn4xzk3mk9ki8y77yjvjr022mr26a822yp05k9ya3a";

        };
        "pkief"."material-icon-theme" = vscode-utils.extensionFromVscodeMarketplace {
          name = "material-icon-theme";
          publisher = "pkief";
          version = "5.20.0";
          sha256 = "1nhmb5x773s23i2clbwqagzhz5zm0v19779kkcqpg6gwyxfcbkb7";

        };
        "jock"."svg" = vscode-utils.extensionFromVscodeMarketplace {
          name = "svg";
          publisher = "jock";
          version = "1.5.4";
          sha256 = "1rcds6i33hj9ljkrpprdbmbskiyckvhi9jmmlhr5i7hjcr9cm4id";

        };
        "mikestead"."dotenv" = vscode-utils.extensionFromVscodeMarketplace {
          name = "dotenv";
          publisher = "mikestead";
          version = "1.0.1";
          sha256 = "0rs57csczwx6wrs99c442qpf6vllv2fby37f3a9rhwc8sg6849vn";

        };
        "mtxr"."sqltools-driver-mysql" = vscode-utils.extensionFromVscodeMarketplace {
          name = "sqltools-driver-mysql";
          publisher = "mtxr";
          version = "0.6.4";
          sha256 = "0fw4w5pfw91s8lbam1k81g9vwjgrpn93dd05lr7r9rgzdw102fcf";

        };
        "fill-labs"."dependi" = vscode-utils.extensionFromVscodeMarketplace {
          name = "dependi";
          publisher = "fill-labs";
          version = "0.7.13";
          sha256 = "1dsd4qal7wmhhbzv5jmcrf8igm20dnr256s2gp1m5myhj08qlzay";

        };
        "mtxr"."sqltools" = vscode-utils.extensionFromVscodeMarketplace {
          name = "sqltools";
          publisher = "mtxr";
          version = "0.28.4";
          sha256 = "0bszagbm10004rx2jdhg2g33wg0f1l0kp3cs1jzkdj1r4an9w5qk";

        };
        "franneck94"."vscode-python-dev-extension-pack" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-python-dev-extension-pack";
          publisher = "franneck94";
          version = "2.0.0";
          sha256 = "0icws51p3kzvi0wd95db9infvjfdgklrn1nyv9qw6zr6scdmzwdm";

        };
        "kisstkondoros"."vscode-gutter-preview" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-gutter-preview";
          publisher = "kisstkondoros";
          version = "0.32.2";
          sha256 = "1b8rp41j99li2718599lrvr8y49h8vlz20vzl1wxdjxhdd8gi2i4";

        };
        "formulahendry"."auto-complete-tag" = vscode-utils.extensionFromVscodeMarketplace {
          name = "auto-complete-tag";
          publisher = "formulahendry";
          version = "0.1.0";
          sha256 = "14xmglw17wlzsil9dpbnn96kvzavfds6xmyf4s9crxydm1swpgsz";

        };
        "reditorsupport"."r" = vscode-utils.extensionFromVscodeMarketplace {
          name = "r";
          publisher = "reditorsupport";
          version = "2.8.4";
          sha256 = "1jbdd74v2myr47ld4r703hyzpisl61canzbghlqgza1fjpygsm61";

        };
        "mtxr"."sqltools-driver-pg" = vscode-utils.extensionFromVscodeMarketplace {
          name = "sqltools-driver-pg";
          publisher = "mtxr";
          version = "0.5.5";
          sha256 = "0fwjkn0aicfv9b5y1d7pjxpz9mdchs7ygidiyf8gcn2j65q34p07";

        };
        "mtxr"."sqltools-driver-sqlite" = vscode-utils.extensionFromVscodeMarketplace {
          name = "sqltools-driver-sqlite";
          publisher = "mtxr";
          version = "0.5.2";
          sha256 = "0rfs00s3im85b3ip1af1jv4qf33dcx8wzr9nlfl08sbjb4b20gk9";

        };
        "usernamehw"."errorlens" = vscode-utils.extensionFromVscodeMarketplace {
          name = "errorlens";
          publisher = "usernamehw";
          version = "3.23.0";
          sha256 = "100fp73c7pvnlmvc6bxxi7almbl2p58p2291zp6ajgxzix9wjgcv";

        };
        "dotjoshjohnson"."xml" = vscode-utils.extensionFromVscodeMarketplace {
          name = "xml";
          publisher = "dotjoshjohnson";
          version = "2.5.1";
          sha256 = "1v4x6yhzny1f8f4jzm4g7vqmqg5bqchyx4n25mkgvw2xp6yls037";

        };
        "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
          name = "even-better-toml";
          publisher = "tamasfe";
          version = "0.21.2";
          sha256 = "0208cms054yj2l8pz9jrv3ydydmb47wr4i0sw8qywpi8yimddf11";

        };
        "mkhl"."shfmt" = vscode-utils.extensionFromVscodeMarketplace {
          name = "shfmt";
          publisher = "mkhl";
          version = "1.3.1";
          sha256 = "0zp1lhx0l9nyrpsdws6jmrjqi7bkdj3mzx7l1d5l56cv0qzmgfjp";

        };
        "pranaygp"."vscode-css-peek" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-css-peek";
          publisher = "pranaygp";
          version = "4.4.3";
          sha256 = "05b2xrrhjss7icm2w0xqb6j5wbqy1lrxh92ihjwkqfgn7fjad3x1";

        };
        "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
          name = "nix-ide";
          publisher = "jnoortheen";
          version = "0.4.12";
          sha256 = "0rdq9wnqfrj8k1g5fcaam5iahzd16bdpi3sa0n2gi0rh02kg55fy";

        };
        "anseki"."vscode-color" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-color";
          publisher = "anseki";
          version = "0.4.5";
          sha256 = "01nl3mpad91xdwz5f71s6b675wvhnj481sjpk8qlvzws1an4mjf5";

        };
        "christian-kohler"."path-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
          name = "path-intellisense";
          publisher = "christian-kohler";
          version = "2.10.0";
          sha256 = "06x9ksl4bghfpxh4n65d1d7dr11spl140p9ch4mc01nrdibgckbc";

        };
      }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {
          "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-xml";
            publisher = "redhat";
            version = "0.28.2025030408";
            sha256 = "1fq9rxsmq5x0qx64yays02qzgkg0vimrx3cbs88q3svbk8h2iyza";
            arch = "linux-x64";

          };
          "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "rust-analyzer";
            publisher = "rust-lang";
            version = "0.4.2331";
            sha256 = "1np5l05s9dx62hc3p3fc891ahzfnh8yqprw9ddnq091kvhhkjx5k";
            arch = "linux-x64";

          };
        }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {
        "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rust-analyzer";
          publisher = "rust-lang";
          version = "0.4.2331";
          sha256 = "0f31927l8ssxlqi89lj9d47qk55hq3xkg1d1cmz5x0lmgbxyv4wc";
          arch = "linux-arm64";

        };
      }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {
      "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
        name = "vscode-xml";
        publisher = "redhat";
        version = "0.28.2025030408";
        sha256 = "1kvbqgn0773nrv65dm7l8lf9bigwzfjvv37wqqs1phyl8hxr2scx";
        arch = "darwin-x64";

      };
      "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
        name = "rust-analyzer";
        publisher = "rust-lang";
        version = "0.4.2331";
        sha256 = "14b6m5nnk9y1a1vs8jawgkj6rbr6ccybzqilx4lix1g59smdmnpd";
        arch = "darwin-x64";

      };
    }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {
    "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
      name = "rust-analyzer";
      publisher = "rust-lang";
      version = "0.4.2331";
      sha256 = "1mc0jnbf1a4398pgix99qnll13bwwk1p5z89k9c9v8mxxbz4kmvy";
      arch = "darwin-arm64";

    };
    "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
      name = "vscode-xml";
      publisher = "redhat";
      version = "0.28.2025030408";
      sha256 = "1mqmg8df7p9f13ln4nza0jgv78xf24rwipxflp7m00m07vc503g1";
      arch = "darwin-arm64";

    };
  })

