vscode_version = "1.97.2"

extensions = [
 "bierner.color-info",
 "franneck94.vscode-c-cpp-dev-extension-pack",
 "13xforever.language-x86-64-assembly",
 "bbenoist.doxygen",
 "cheshirekow.cmake-format",
 "cschlosser.doxdocgen",
 "franneck94.c-cpp-runner",
 "franneck94.vscode-c-cpp-config",
 "jeff-hykin.better-cpp-syntax",
 "ms-vscode.cpptools-themes",
 "franneck94.vscode-python-config",
 "franneck94.vscode-python-dev-extension-pack",
 "ms-python.mypy-type-checker",
 "njqdev.vscode-python-typehint",
 "franneck94.workspace-formatter",
 "fwcd.kotlin",
 "gruntfuggly.activitusbar",
 "hangxingliu.vscode-nginx-conf-hint",
 "htmlhint.vscode-htmlhint",
 "kisstkondoros.vscode-gutter-preview",
 "kokororin.vscode-phpfmt",
 "mkhl.shfmt",
 "mtxr.sqltools",
 "mtxr.sqltools-driver-mssql",
 "mtxr.sqltools-driver-mysql",
 "mtxr.sqltools-driver-pg",
 "mtxr.sqltools-driver-sqlite",
 "pranaygp.vscode-css-peek",
 "psioniq.psi-header",
 "rdebugger.r-debugger",
 "swellaby.vscode-rust-test-adapter",
 "zignd.html-css-class-completion",
]
