vscode_version = "1.91.2"

extensions = [
 "anseki.vscode-color",
 "christian-kohler.path-intellisense",
 "dotjoshjohnson.xml",
 "esbenp.prettier-vscode",
 "fill-labs.dependi",
 "formulahendry.auto-complete-tag",
 "formulahendry.code-runner",
 "franneck94.vscode-c-cpp-dev-extension-pack",
 "franneck94.vscode-python-dev-extension-pack",
 "franneck94.workspace-formatter",
 "fwcd.kotlin",
 "gitlab.gitlab-workflow",
 "golang.go",
 "gruntfuggly.activitusbar",
 "hangxingliu.vscode-nginx-conf-hint",
 "htmlhint.vscode-htmlhint",
 "jnoortheen.nix-ide",
 "jock.svg",
 "kisstkondoros.vscode-gutter-preview",
 "kokororin.vscode-phpfmt",
 "mikestead.dotenv",
 "mkhl.shfmt",
 "ms-vscode.live-server",
 "mtxr.sqltools",
 "mtxr.sqltools-driver-mssql",
 "mtxr.sqltools-driver-mysql",
 "mtxr.sqltools-driver-pg",
 "mtxr.sqltools-driver-sqlite",
 "naumovs.color-highlight",
 "pkief.material-icon-theme",
 "pkief.material-product-icons",
 "pranaygp.vscode-css-peek",
 "psioniq.psi-header",
 "rdebugger.r-debugger",
 "rebornix.ruby",
 "redhat.vscode-xml",
 "redhat.vscode-yaml",
 "reditorsupport.r",
 "rust-lang.rust-analyzer",
 "swellaby.vscode-rust-test-adapter",
 "tamasfe.even-better-toml",
 "usernamehw.errorlens",
 "vscjava.vscode-java-pack",
 "waderyan.gitblame",
 "wingrunr21.vscode-ruby",
 "yzane.markdown-pdf",
 "yzhang.markdown-all-in-one",
 "zhuangtongfa.material-theme",
 "zignd.html-css-class-completion",
]
